import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(scriptDir, "..");
const tokensPath = resolve(webRoot, "src", "design", "motion-tokens.json");
const cssPath = resolve(webRoot, "src", "design", "motion-system.generated.css");
const checkMode = process.argv.includes("--check");

const tokens = JSON.parse(readFileSync(tokensPath, "utf8"));

function bezier(name) {
  const value = tokens.easings[name];
  if (!value) {
    throw new Error(`Unknown easing ${name}.`);
  }
  return `cubic-bezier(${value.join(", ")})`;
}

// Keyframe bodies are hand-authored per primitive semantics (transform/opacity
// only, so they are GPU-safe and vestibular-safe). Loop is decided by the token
// file, not here, so the honesty rule "only active primitives loop" is auditable.
const keyframeBodies = {
  settle: "  from { transform: scale(0.994); opacity: 0.55; }\n  to { transform: none; opacity: 1; }",
  hover:
    "  0%, 100% { transform: translateY(0); opacity: 0.9; }\n  50% { transform: translateY(-1.5px); opacity: 1; }",
  resolve:
    "  0% { transform: translateX(-32%); opacity: 0.35; }\n  55% { opacity: 1; }\n  100% { transform: translateX(132%); opacity: 0.35; }",
  pause: "  from { transform: translateY(-1px); opacity: 1; }\n  to { transform: none; opacity: 0.9; }",
  recoil:
    "  0% { transform: translateX(0); }\n  25% { transform: translateX(-3px); }\n  60% { transform: translateX(1px); }\n  100% { transform: none; }",
  downgrade: "  0% { opacity: 1; }\n  50% { opacity: 0.68; }\n  100% { opacity: 1; }",
};

function buildCss() {
  const lines = [
    "/* This file is generated by scripts/generate_motion_system.mjs. Do not edit by hand. */",
    "/* Single source: src/design/motion-tokens.json. Motion is causality: every primitive answers a real question. */",
    ":root {",
  ];
  for (const [name, ms] of Object.entries(tokens.durationsMs)) {
    lines.push(`  --df-motion-${name}: ${ms}ms;`);
  }
  lines.push(`  --df-ease-standard: ${bezier("standard")};`);
  lines.push(`  --df-ease-emphasized: ${bezier("emphasized")};`);
  lines.push(`  --df-ease-exit: ${bezier("exit")};`);
  lines.push("}");
  lines.push("");

  for (const [name, spec] of Object.entries(tokens.primitives)) {
    if (name === "still") {
      continue; // stillness has no keyframe by definition
    }
    lines.push(`@keyframes df-${name} {`);
    lines.push(keyframeBodies[name]);
    lines.push("}");
    lines.push("");
  }

  lines.push("/* Primitive utility classes. Loop is sourced from motion-tokens.json. */");
  for (const [name, spec] of Object.entries(tokens.primitives)) {
    if (name === "still") {
      lines.push(".df-motion-still {");
      lines.push("  animation: none;");
      lines.push("}");
      lines.push("");
      continue;
    }
    const iteration = spec.loop ? "infinite" : "1";
    const fill = spec.loop ? "none" : "both";
    lines.push(`.df-motion-${name} {`);
    lines.push(
      `  animation: df-${name} var(--df-motion-${spec.duration}) var(--df-ease-${spec.easing}) ${iteration} ${fill};`,
    );
    lines.push("}");
    lines.push("");
  }

  // Reduced-motion twin: primitives collapse to their meaning-preserving static
  // state (no movement) but never change rung. Form/color/text carry meaning.
  lines.push("@media (prefers-reduced-motion: reduce) {");
  for (const name of Object.keys(tokens.primitives)) {
    if (name === "still") {
      continue;
    }
    lines.push(`  .df-motion-${name} {`);
    lines.push("    animation: none;");
    lines.push("  }");
  }
  lines.push("}");
  lines.push("");

  return `${lines.join("\n")}\n`;
}

function assertCurrent(filePath, nextBody) {
  if (!existsSync(filePath)) {
    throw new Error(`${filePath} is missing. Run npm run motion.`);
  }
  if (readFileSync(filePath, "utf8") !== nextBody) {
    throw new Error(`${filePath} is out of date. Run npm run motion.`);
  }
}

const css = buildCss();

if (checkMode) {
  assertCurrent(cssPath, css);
  console.log("Motion system artifacts are up to date.");
} else {
  mkdirSync(dirname(cssPath), { recursive: true });
  writeFileSync(cssPath, css);
  console.log("Generated DataForge motion system artifacts.");
}
