import { describe, expect, it } from "vitest";
import {
  PROOF_ATTRIBUTION_ASYMMETRY,
  parseUnsatCore,
  parseUnsatCoreLabel,
} from "./observatory";

// Label shapes are generated by SchemaToSMT in dataforge/verifier/smt.py. Each case
// below mirrors one assert_and_track site, so a change to the encoder's label
// format fails here rather than silently degrading to raw strings in the UI.
describe("unsat core decoding: which constraint blocked this cell", () => {
  it("decodes a functional dependency, including a composite determinant", () => {
    const single = parseUnsatCoreLabel("fd::ProviderNumber::City::row::418");
    expect(single?.kind).toBe("fd");
    expect(single?.columns).toEqual(["ProviderNumber"]);
    expect(single?.dependent).toBe("City");
    expect(single?.row).toBe(418);
    expect(single?.sentence).toContain("ProviderNumber");
    expect(single?.sentence).toContain("City");
    expect(single?.sentence).toContain("418");

    const composite = parseUnsatCoreLabel("fd::MeasureCode+State::Condition::row::7");
    expect(composite?.columns).toEqual(["MeasureCode", "State"]);
    expect(composite?.dependent).toBe("Condition");
  });

  it("decodes both domain bounds distinctly", () => {
    const lower = parseUnsatCoreLabel("domain::rating::min::row::5");
    const upper = parseUnsatCoreLabel("domain::rating::max::row::5");
    expect(lower?.bound).toBe("min");
    expect(upper?.bound).toBe("max");
    expect(lower?.sentence).not.toBe(upper?.sentence);
    expect(lower?.columns).toEqual(["rating"]);
  });

  it("decodes every remaining label shape the verifier emits", () => {
    const cases: Array<[string, string]> = [
      ["not_null::city::row::2", "Required value"],
      ["primary_key_not_null::id::row::2", "Primary key"],
      ["unique::id::row::9", "Uniqueness"],
      ["primary_key_unique::id::row::9", "Primary key uniqueness"],
      ["accepted_values::state::row::3", "Allowed values"],
      ["regex::zip::row::4", "Format pattern"],
    ];
    for (const [label, kindLabel] of cases) {
      const parsed = parseUnsatCoreLabel(label);
      expect(parsed, label).not.toBeNull();
      expect(parsed?.kindLabel).toBe(kindLabel);
      expect(parsed?.row).not.toBeNull();
      // No raw token may leak into the sentence a human reads.
      expect(parsed?.sentence).not.toContain("::");
      expect(parsed?.sentence).not.toContain("_");
    }
  });

  it("drops labels it cannot parse rather than rendering a guess", () => {
    expect(parseUnsatCoreLabel("something_unexpected")).toBeNull();
    expect(parseUnsatCoreLabel("")).toBeNull();
    expect(parseUnsatCoreLabel("brand_new_kind::col::row::1")).toBeNull();
    expect(parseUnsatCore(["fd::a::b::row::1", "garbage"])).toHaveLength(1);
    expect(parseUnsatCore(null)).toEqual([]);
    expect(parseUnsatCore(undefined)).toEqual([]);
  });

  it("tolerates a label with no row suffix", () => {
    const parsed = parseUnsatCoreLabel("unique::id");
    expect(parsed?.row).toBeNull();
    expect(parsed?.sentence).not.toContain("row");
  });

  it("states the accept/reject asymmetry rather than implying symmetry", () => {
    // An accepted cell has no unsat core; claiming a positive proof trace for it
    // would be the kind of symmetric-looking display L3 forbids.
    expect(PROOF_ATTRIBUTION_ASYMMETRY).toContain("do not carry a positive proof trace");
    expect(PROOF_ATTRIBUTION_ASYMMETRY.toLowerCase()).toContain("re-verify");
  });
});
